Fix `resizeImage(...)`
nextcloud/ios-communication-library pull request #107
Opened 2021-12-21 13:49 UTC by thisIsTheFoxe

There was a problem with `vImageScale_ARGB8888(...)`which would cause a runtime error: EXC_BAD_ACCESS.
Using UIGraphicsContext is Swiftier, more readable, and safer, since it fixes the error and avoids handling raw pointers / buffers.

Fix in the Nextcloud/iOS repo: Nextcloud/ios@1c4bbef9b093a0ed4da85ce468eef71d4fbabd95

<hr/>

**Fun fact:** This file was created exactly one year ago 😄

2021-12-21 14:12 UTC, marinofaggiana commented
... but the algorithm  with UIGraphicsContext  bad resize, completely bad

2021-12-21 14:13 UTC, marinofaggiana requested changes
usual wrong algorithm

2021-12-21 15:03 UTC, thisIsTheFoxe commented
I'm not sure what you mean, it works fine for me and it is a lot better and saver as mentioned in the PR.
I'm also unsure which *changes* you are *requesting*, please elaborate...

- And well, if it is so *bad* why is it used in the app itself? 
- How is it *bad* / *wrong*?
- Why did you replace it?
- How do you suggest we fix the issue?

2021-12-21 15:19 UTC, marinofaggiana commented
> I'm not sure what you mean, it works fine for me and it is a lot better and saver as mentioned in the PR. I'm also unsure which _changes_ you are _requesting_, please elaborate...
> 
> * And well, if it is so _bad_ why is it used in the app itself?
> * How is it _bad_ / _wrong_?
> * Why did you replace it?
> * How do you suggest we fix the issue?

There will be a reason why I used this dangerous algorithm instead of the very simple one (only 4 line of code)? 

Why didn't you ask before working on it ?

I have use this algorithm because the results of resize is excellent, the comparison with UIGraphicsContext "was" incredible (try it with an BIG image) now I knows that I used the UIGraphicsGetImageFromCurrentImageContext in Nextcloud iOS but the comparison was visibly different, but you can create a test for this 2 different algorithm (you did it ?), if something has changed and better I'm happy to replace it, but attention also the UIGraphicsGetImageFromCurrentImageContext crashes often with big files.

2021-12-22 10:09 UTC, thisIsTheFoxe commented
> There will be a reason why I used this dangerous algorithm instead of the very simple one (only 4 line of code)?

Not sure what you mean.. The change to UIKit was made **after** (Jan '21) using the Accelerate technique (Dec '20). And btw, wouldn't it be great to know the reason for that? That's why explicit commit messages are important as well as documenting changes in PRs like this etc.

> Why didn't you ask before working on it ?

-  because I just found it and it's a high-severity bug (causing runtime crashes)
- because it's an _easy_ fix
- because documenting the work in a PR as I am doing now, improves documentation and encourages further development & communication

> comparison with UIGraphicsContext "was" incredible (try it with an BIG image) [...] but you can create a test for this 2 different algorithm (you did it ?), if something has changed and better I'm happy to replace it, but attention also the UIGraphicsGetImageFromCurrentImageContext crashes often with big files.

I tested it and downsampling seems to work and always looks the same as UIKit, no crashes (tested with up to 8k `.png` with >17MB).
The real problem is with upsampling images, which usually cause the Accelerate function to crash at runtime as mentioned. When used on the main queue it doesn't crash, but it's clear that something goes wrong.

Accelerate (as it is now, but using the `.response(queue: .main)` queue): 
![IMG_2022](https://user-images.githubusercontent.com/18512366/147073994-25122e7a-eb2f-47f5-8c8f-7a5d4b6a37e9.jpg)

UIKit (using default `.response(queue: NCCommunicationCommon.backgroundQueue)`):
![IMG_2023](https://user-images.githubusercontent.com/18512366/147074602-d2b0e98f-69bc-4b6f-a245-7b2813b1199a.jpg)

2021-12-22 10:46 UTC, marinofaggiana commented
Thanks @thisIsTheFoxe I don't understand, used in .main or .background ... using it in .main would slow down too much ... we are obliged to use it in the background (example Media)

2021-12-22 11:33 UTC, thisIsTheFoxe commented
@marinofaggiana yes, that's why I'm using UIKit so it can run in the background without crashing.

2022-01-04 08:57 UTC, marinofaggiana approved these changes

2022-01-04 08:57 UTC, merged